name: Setup & Install dependencies
description: Setup node, EAS, and install dependencies
inputs:
  expo-token:
    description: 'Expo token'
    required: true
  is-deploy:
    description: 'Is this action deploy and need to Setup EAS?'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup EAS
      if: inputs.is-deploy == 'true'
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-version: latest
        expo-cache: true
        token: ${{ inputs.expo-token }}

    - name: Install eas-cli globally
      if: inputs.is-deploy == 'true'
      run: npm install -g eas-cli
      shell: bash

    - name: Check eas
      run: |
        which eas
        eas --version
      shell: bash
        
    - name: Caching dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-cache-${{ runner.os }}-
        
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash