name: Setup & Install dependencies
description: Setup node, EAS, and install dependencies
inputs:
  expo-token:
    description: 'Expo token'
    required: true
  is-deploy:
    description: 'Is this action deploy and need to Setup EAS?'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup EAS
      if: inputs.is-deploy == 'true'
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-version: latest
        expo-cache: true
        token: ${{ inputs.expo-token }}

    - name: Caching CI dependencies
      if: inputs.is-deploy == 'false'
      id: cacheci
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-cache-${{ runner.os }}-

    - name: Caching deployment dependencies
      if: inputs.is-deploy == 'true'
      id: cachedeploy
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install CI dependencies
      if: steps.cacheci.outputs.cache-hit != 'true' && inputs.is-deploy == 'false'
      run: npm ci
      shell: bash

    - name: Install deployment dependencies
      if: steps.cachedeploy.outputs.cache-hit != 'true' && inputs.is-deploy == 'true'
      run: npm ci
      shell: bash