name: Deploy App to Android
on:
  workflow_dispatch:
jobs:         
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
      
    - name: Setup & Install dependencies
      uses: ./.github/setup-envs
      with:
        expo-token: ${{ secrets.EXPO_TOKEN }}
        is-deploy: 'true'
      
    - name: Build app in Android
      run: eas build --profile preview --platform android --non-interactive

    - name: Get latest build URL
      id: get-url
      run: |
        url=$(eas build:list --platform android --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
        echo "APK_URL=$url" >> $GITHUB_ENV

    - name: Show deploy URL
      run: |
        echo "✅ APK file available at: $APK_URL"
