name: Deploy App to Android
on:
  workflow_dispatch:
jobs:         
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
      
    - name: Setup environments
      uses: ./.github/setup-envs
      with:
        expo-token: ${{ secrets.EXPO_TOKEN }}
      
    - name: Build app in Android
      run: eas build --profile preview --platform android --non-interactive --local --output ${{ github.workspace }}/pill-pal-release.apk
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pill-pal-release
        path: ${{ github.workspace }}/pill-pal-release.apk

    - name: Successful deploy
      run: echo "Deploy successfully"