name: Deploy App to Android
on:
  workflow_dispatch:
jobs:         
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
      
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-version: latest
        expo-cache: true
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Caching
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
      
    - name: Build app in Android
      run: eas build --profile preview --platform android --non-interactive --local --output ${{ github.workspace }}/pill-pal-release.apk
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pill-pal-release
        path: ${{ github.workspace }}/pill-pal-release.apk

    - name: Successful deploy
      run: echo "Deploy successfully"
