name: Deploy App to IOS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        
      - name: Setup environments
        uses: ./.github/setup-envs
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
        
      - name: Lint code
        run: npm run lint
              
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
      
    - name: Setup environments
      uses: ./.github/setup-envs
      with:
        expo-token: ${{ secrets.EXPO_TOKEN }}
      
    - name: Build app in IOS
      if: false
      run: eas build --profile preview --platform ios --non-interactive --clear-cache --local --output ${{ github.workspace }}/pill-pal-release.ipa
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pill-pal-release
        path: ${{ github.workspace }}/pill-pal-release.ipa

    - name: Successful deploy
      run: echo "Deploy successfully"